name: Bandit
on: 
  pull_request:
  push:
    branches:
    - main

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Bandit Report
      uses: libertyy/py3-bandit-check@v2
    - name: Save Bandit txt Report
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        path: ${{ RUNNER.temp }}/_github_home/bandit_report.out
